/*
Derrick Fox
CS 226
April 22, 2014
Inventory Reporter
*/

#include <iostream>
// Include the class file for the user defined Inventory class.
#include "Inventory.h"
#include <iomanip>
using namespace std;

int main() {
	// Create variables to hold values for cost of item, number of items left in inventory, and the quantity of items ordered.
	double cost;
	int itemNum, quantity;

	// Create Inventory objects and itialize them.
	Inventory item1;
	Inventory item2(555, 5.98, 45);
	Inventory item3;

	// User input data about items.
	cout << fixed << showpoint << setprecision(2);
	cout << "Enter the cost of an inventory item." << endl;
	cin >> cost;
	while (cost <= 0) {
		cout << "Really? This item is free or less than free?...try again." << endl;
		cin >> cost;
	}
	item3.setCost(cost);

	cout << "Enter the inventory number for the item." << endl;
	cin >> itemNum;
	while (itemNum <= 0) {
		cout << "Really? You want to assign zero or a negative number as an item number?...Try again." << endl;
		cin >> itemNum;
	}
	item3.setItemNumber(itemNum);

	cout << "Enter the quantity of the item." << endl;
	cin >> quantity;
	while (quantity <= 0) {
		cout << "Really? You have none or less than none?...Try again" << endl;
		cin >> quantity;
	}
	item3.setQuantity(quantity);
	item3.setTotalCost();

	// Generate an Inventory Report to the users by invoking functions from the Inventory class. 
	cout << "Item 1: " << endl;
	cout << "Cost: $" << item1.getCost() << endl;
	cout << "Item Number : " << item1.getItemNumber() << endl;
	cout << "Number of items left: " << item1.getQuantity() << endl;
	cout << "Total cost of items in inventory: $" << item1.getTotalCost() << endl;
	cout << "(I demonstrate an empty constructory.)" << endl;
	cout << endl;

	cout << "Item 2: " << endl;
	cout << "Cost: $" << item2.getCost() << endl;
	cout << "Item Number : " << item2.getItemNumber() << endl;
	cout << "Number of items left: " << item2.getQuantity() << endl;
	cout << "Total cost of items in inventory: $" << item2.getTotalCost() << endl;
	cout << "(I demonstrate an overloaded constructor defined by they programmer.)" << endl;
	cout << endl;

	cout << "Item 3: " << endl;
	cout << "Cost: $" << item3.getCost() << endl;
	cout << "Item Number : " << item3.getItemNumber() << endl;
	cout << "Number of items left: " << item3.getQuantity() << endl;
	cout << "Total cost of items in inventory: $" << item3.getTotalCost() << endl;
	cout << "(I demonstrate an overloaded constructor generated by user input.)" << endl;
	cout << endl;

	system("pause");
	return 0;
}